# Generated by Django 5.1.7 on 2025-03-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Erkak'), ('Female', 'Ayol')], default='Male', max_length=10),
        ),
    ]
