# Generated by Django 5.1.7 on 2025-03-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_alter_favorite_unique_together_remove_site_dislikes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
